{% set version = "1.77" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sparsem
  version: {{ version|replace("-", "_") }}

source:
  fn: SparseM_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/SparseM_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/SparseM/SparseM_{{ version }}.tar.gz


  sha256: a9329fef14ae4fc646df1f4f6e57efb0211811599d015f7bc04c04285495d45c

build:
  merge_build_host: True  # [win]
  number: 1

  rpaths:
    - lib/R/lib/
    - lib/
  skip: True  # [win32]


requirements:
  build:
    - posix                # [win]
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('SparseM')"  # [not win]
    - "\"%R%\" -e \"library('SparseM')\""  # [win]



about:
  home: http://www.econ.uiuc.edu/~roger/research/sparse/sparse.html
  license: GPL (>= 2)
  summary: 'Some basic linear algebra functionality for sparse matrices is provided:  including
    Cholesky decomposition and backsolving as well as  standard R subsetting and Kronecker
    products.'

  license_family: GPL3



extra:
  recipe-maintainers:
    - croth1
