appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: SUS9YgMUulWfJXobNscq0LqmfXXOzMoGpDw97Zy7kMjLy0ajhBfX7q+UrFK3nNksPFH3dOsHM5ABvYDtdHZPEnTJcZ1YNgf6OkeeHuAs9H/MEsBQ67uLmLxa3AXh09WZwCSNn1UGih4l0HpWSn8ZUH7IMqWUfBclooDZ2VXQff3M96LX6K0FmzdXQ2g7AvQRFskWoaPuHowtuLvjF9rw+IxJCntz5hyze3OXdxcYAnarzVrQBQrXRjHX0TJ4nJPyz1njNUlZSJafxAuhSZG/HoLY+QfifjwstdU3fIH3LdX3tb8OilvKT+kh0zCzgWAaJq0Z/tvOAnWwXGe50s0Dv3AGg7cQA1/UUUjoFF/iCKtoPO4lmqmXfjAAtswDcx9AVTXuXw0ZUa/q7vYotc+RYayXcCO0fnRiEG8xmsE3/sDO/AlSVLBn5Z4E+8k5K/FdPR/fYbOAde9/00/0fUO6ITHqA0TrGFy7RFoaXRUwarmbx4uwEU8jhF2DIc9eGLvRkNJ7qgWySJ8Gg97336DD1K7+3NaPkULU+UkgdFJ+wnTp6//pjFsneNvTnCEHDPGI0PPzvDWG8fGfLsc+IaPyjQBxLGbEgK5ux4vE7hWA0R+FTFideNntndSJatsXfVI1jfYOdGyH0Dy6SpzmzKJcrBZG+L58UX/JLa24xwVvObo=}
bot:
  automerge: true
